# Skilling 3

In [2]:
import pandas as pd

In [4]:
df=pd.read_csv('Hospital General Information.csv', encoding="ISO-8859-1")
df

,Provider ID,Hospital Name,Address,City,State,ZIP Code,County Name,Phone Number,Hospital Type,Hospital Ownership,...,Readmission national comparison,Readmission national comparison footnote,Patient experience national comparison,Patient experience national comparison footnote,Effectiveness of care national comparison,Effectiveness of care national comparison footnote,Timeliness of care national comparison,Timeliness of care national comparison footnote,Efficient use of medical imaging national comparison,Efficient use of medical imaging national comparison footnote
0,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,3347938701,Acute Care Hospitals,Government - Hospital District or Authority,...,Same as the national average,NaN,Below the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,Same as the national average,NaN
1,10005,MARSHALL MEDICAL CENTER SOUTH,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,2565938310,Acute Care Hospitals,Government - Hospital District or Authority,...,Above the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,Above the national average,NaN,Below the national average,NaN
2,10006,ELIZA COFFEE MEMORIAL HOSPITAL,205 MARENGO STREET,FLORENCE,AL,35631,LAUDERDALE,2567688400,Acute Care Hospitals,Government - Hospital District or Authority,...,Same as the national average,NaN,Below the national average,NaN,Same as the national average,NaN,Above the national average,NaN,Same as the national average,NaN
3,10007,MIZELL MEMORIAL HOSPITAL,702 N MAIN ST,OPP,AL,36467,COVINGTON,3344933541,Acute Care Hospitals,Voluntary non-profit - Private,...,Below the national average,NaN,Same as the national average,NaN,Below the national average,NaN,Above the national average,NaN,Not Available,Results are not available for this reporting p...
4,10008,CRENSHAW COMMUNITY HOSPITAL,101 HOSPITAL CIRCLE,LUVERNE,AL,36049,CRENSHAW,3343353374,Acute Care Hospitals,Proprietary,...,Same as the national average,NaN,Not Available,Results are not available for this reporting p...,Same as the national average,NaN,Above the national average,NaN,Not Available,Results are not available for this reporting p...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4807,670118,FIRST TEXAS HOSPITAL,9922 LOUETTA RD,HOUSTON,TX,77070,HARRIS,8442641435,Acute Care Hospitals,Proprietary,...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...
4808,640001,LBJ TROPICAL MEDICAL CENTER,FAGAALU VILLAGE,PAGO PAGO,AS,96799,NaN,6846334590,Acute Care Hospitals,Government - Hospital District or Authority,...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...
4809,650001,GUAM MEMORIAL HOSPITAL AUTHORITY,85O GOV CARLOS G CAMACHO ROAD,TAMUNING,GU,96913,NaN,6716472552,Acute Care Hospitals,Government - Local,...,Same as the national average,NaN,Not Available,Results are not available for this reporting p...,Same as the national average,NaN,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...
4810,650003,GUAM REGIONAL MEDICAL CITY,133 ROUTE 3,DEDEDO,GU,96929,NaN,6716455500,Acute Care Hospitals,Voluntary non-profit - Private,...,Not Available,Data are shown only for hospitals that partici...,Not Available,Data are shown only for hospitals that partici...,Not Available,Data are shown only for hospitals that partici...,Not Available,Data are shown only for hospitals that partici...,Not Available,Data are shown only for hospitals that partici...
4811,660001,COMMONWEALTH HEALTH CENTER,"PO BOX 409CK, NAVY HILL ROAD",GARAPAN,MP,96950,NaN,6702348950,Acute Care Hospitals,Proprietary,...,Below the national average,NaN,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...

In [5]:
df=df.fillna(method='ffill')

In [6]:
df

,Provider ID,Hospital Name,Address,City,State,ZIP Code,County Name,Phone Number,Hospital Type,Hospital Ownership,...,Readmission national comparison,Readmission national comparison footnote,Patient experience national comparison,Patient experience national comparison footnote,Effectiveness of care national comparison,Effectiveness of care national comparison footnote,Timeliness of care national comparison,Timeliness of care national comparison footnote,Efficient use of medical imaging national comparison,Efficient use of medical imaging national comparison footnote
0,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,3347938701,Acute Care Hospitals,Government - Hospital District or Authority,...,Same as the national average,NaN,Below the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,Same as the national average,NaN
1,10005,MARSHALL MEDICAL CENTER SOUTH,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,2565938310,Acute Care Hospitals,Government - Hospital District or Authority,...,Above the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,Above the national average,NaN,Below the national average,NaN
2,10006,ELIZA COFFEE MEMORIAL HOSPITAL,205 MARENGO STREET,FLORENCE,AL,35631,LAUDERDALE,2567688400,Acute Care Hospitals,Government - Hospital District or Authority,...,Same as the national average,NaN,Below the national average,NaN,Same as the national average,NaN,Above the national average,NaN,Same as the national average,NaN
3,10007,MIZELL MEMORIAL HOSPITAL,702 N MAIN ST,OPP,AL,36467,COVINGTON,3344933541,Acute Care Hospitals,Voluntary non-profit - Private,...,Below the national average,NaN,Same as the national average,NaN,Below the national average,NaN,Above the national average,NaN,Not Available,Results are not available for this reporting p...
4,10008,CRENSHAW COMMUNITY HOSPITAL,101 HOSPITAL CIRCLE,LUVERNE,AL,36049,CRENSHAW,3343353374,Acute Care Hospitals,Proprietary,...,Same as the national average,NaN,Not Available,Results are not available for this reporting p...,Same as the national average,NaN,Above the national average,NaN,Not Available,Results are not available for this reporting p...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4807,670118,FIRST TEXAS HOSPITAL,9922 LOUETTA RD,HOUSTON,TX,77070,HARRIS,8442641435,Acute Care Hospitals,Proprietary,...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...
4808,640001,LBJ TROPICAL MEDICAL CENTER,FAGAALU VILLAGE,PAGO PAGO,AS,96799,HARRIS,6846334590,Acute Care Hospitals,Government - Hospital District or Authority,...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...
4809,650001,GUAM MEMORIAL HOSPITAL AUTHORITY,85O GOV CARLOS G CAMACHO ROAD,TAMUNING,GU,96913,HARRIS,6716472552,Acute Care Hospitals,Government - Local,...,Same as the national average,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Same as the national average,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...
4810,650003,GUAM REGIONAL MEDICAL CITY,133 ROUTE 3,DEDEDO,GU,96929,HARRIS,6716455500,Acute Care Hospitals,Voluntary non-profit - Private,...,Not Available,Data are shown only for hospitals that partici...,Not Available,Data are shown only for hospitals that partici...,Not Available,Data are shown only for hospitals that partici...,Not Available,Data are shown only for hospitals that partici...,Not Available,Data are shown only for hospitals that partici...
4811,660001,COMMONWEALTH HEALTH CENTER,"PO BOX 409CK, NAVY HILL ROAD",GARAPAN,MP,96950,HARRIS,6702348950,Acute Care Hospitals,Proprietary,...,Below the national average,Data are shown only for hospitals that partici...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...

In [7]:
df.head()

,Provider ID,Hospital Name,Address,City,State,ZIP Code,County Name,Phone Number,Hospital Type,Hospital Ownership,...,Readmission national comparison,Readmission national comparison footnote,Patient experience national comparison,Patient experience national comparison footnote,Effectiveness of care national comparison,Effectiveness of care national comparison footnote,Timeliness of care national comparison,Timeliness of care national comparison footnote,Efficient use of medical imaging national comparison,Efficient use of medical imaging national comparison footnote
0,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,3347938701,Acute Care Hospitals,Government - Hospital District or Authority,...,Same as the national average,NaN,Below the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,Same as the national average,NaN
1,10005,MARSHALL MEDICAL CENTER SOUTH,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,2565938310,Acute Care Hospitals,Government - Hospital District or Authority,...,Above the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,Above the national average,NaN,Below the national average,NaN
2,10006,ELIZA COFFEE MEMORIAL HOSPITAL,205 MARENGO STREET,FLORENCE,AL,35631,LAUDERDALE,2567688400,Acute Care Hospitals,Government - Hospital District or Authority,...,Same as the national average,NaN,Below the national average,NaN,Same as the national average,NaN,Above the national average,NaN,Same as the national average,NaN
3,10007,MIZELL MEMORIAL HOSPITAL,702 N MAIN ST,OPP,AL,36467,COVINGTON,3344933541,Acute Care Hospitals,Voluntary non-profit - Private,...,Below the national average,NaN,Same as the national average,NaN,Below the national average,NaN,Above the national average,NaN,Not Available,Results are not available for this reporting p...
4,10008,CRENSHAW COMMUNITY HOSPITAL,101 HOSPITAL CIRCLE,LUVERNE,AL,36049,CRENSHAW,3343353374,Acute Care Hospitals,Proprietary,...,Same as the national average,NaN,Not Available,Results are not available for this reporting p...,Same as the national average,NaN,Above the national average,NaN,Not Available,Results are not available for this reporting p...

In [8]:
df[["Hospital Type","Hospital Ownership"]]

             Hospital Type                           Hospital Ownership
0     Acute Care Hospitals  Government - Hospital District or Authority
1     Acute Care Hospitals  Government - Hospital District or Authority
2     Acute Care Hospitals  Government - Hospital District or Authority
3     Acute Care Hospitals               Voluntary non-profit - Private
4     Acute Care Hospitals                                  Proprietary
...                    ...                                          ...
4807  Acute Care Hospitals                                  Proprietary
4808  Acute Care Hospitals  Government - Hospital District or Authority
4809  Acute Care Hospitals                           Government - Local
4810  Acute Care Hospitals               Voluntary non-profit - Private
4811  Acute Care Hospitals                                  Proprietary

[4812 rows x 2 columns]

In [9]:
df[["Hospital Type","Hospital Ownership"]].describe()

               Hospital Type              Hospital Ownership
count                   4812                            4812
unique                     3                              10
top     Acute Care Hospitals  Voluntary non-profit - Private
freq                    3369                            2052

In [10]:
df["State"].value_counts(sort=True, ascending=True)

AS      1
MP      1
GU      2
VI      2
DE      7
DC      8
RI     11
VT     14
AK     22
HI     23
NH     26
WY     28
CT     31
ME     33
NV     35
NM     41
ID     41
ND     44
UT     46
MD     49
WV     49
PR     52
OR     60
SC     60
SD     60
MT     62
MA     64
NJ     66
AR     75
CO     78
AZ     80
VA     86
NE     89
AL     90
WA     91
KY     94
MS     95
TN    107
NC    107
MO    112
IA    116
IN    120
LA    121
OK    124
WI    126
MN    131
MI    131
GA    133
KS    137
OH    168
NY    171
PA    171
IL    180
FL    187
CA    343
TX    411
Name: State, dtype: int64

In [11]:
df[df["State"]=="TX"][["State","County Name","Provider ID"]]

     State County Name  Provider ID
3954    TX     EL PASO       450002
3955    TX        KERR       450007
3956    TX     WICHITA       450010
3957    TX      BRAZOS       450011
3958    TX      DALLAS       450015
...    ...         ...          ...
4803    TX    COLORADO       670114
4804    TX     LIBERTY       670115
4805    TX     TARRANT       670116
4806    TX   VAN ZANDT       670117
4807    TX      HARRIS       670118

[411 rows x 3 columns]

In [12]:
df[df["State"]=="TX"][["State","Hospital Type","Hospital Ownership"]]

     State         Hospital Type                           Hospital Ownership
3954    TX  Acute Care Hospitals                                  Proprietary
3955    TX  Acute Care Hospitals               Voluntary non-profit - Private
3956    TX  Acute Care Hospitals               Voluntary non-profit - Private
3957    TX  Acute Care Hospitals               Voluntary non-profit - Private
3958    TX  Acute Care Hospitals  Government - Hospital District or Authority
...    ...                   ...                                          ...
4803    TX  Acute Care Hospitals                                  Proprietary
4804    TX  Acute Care Hospitals                                  Proprietary
4805    TX  Acute Care Hospitals  Government - Hospital District or Authority
4806    TX  Acute Care Hospitals                                  Proprietary
4807    TX  Acute Care Hospitals                                  Proprietary

[411 rows x 3 columns]

In [13]:
df[["Hospital Name","Timeliness of care national comparison footnote"]].dropna()

,Hospital Name,Timeliness of care national comparison footnote
83,NORTH ALABAMA SPECIALITY HOSPITAL,Data are shown only for hospitals that partici...
84,WASHINGTON COUNTY HOSPITAL,Data are shown only for hospitals that partici...
85,RED BAY HOSPITAL,Results are not available for this reporting p...
86,CHOCTAW GENERAL HOSPITAL,Results are not available for this reporting p...
87,ST VINCENTS BLOUNT,Results are not available for this reporting p...
...,...,...
4807,FIRST TEXAS HOSPITAL,Results are not available for this reporting p...
4808,LBJ TROPICAL MEDICAL CENTER,Results are not available for this reporting p...
4809,GUAM MEMORIAL HOSPITAL AUTHORITY,Results are not available for this reporting p...
4810,GUAM REGIONAL MEDICAL CITY,Data are shown only for hospitals that partici...
4811,COMMONWEALTH HEALTH CENTER,Results are not available for this reporting p...

In [14]:
df.loc[(df["Hospital Type"]=="Acute Care Hospitals")&(df["Hospital overall rating"]=="4")]

,Provider ID,Hospital Name,Address,City,State,ZIP Code,County Name,Phone Number,Hospital Type,Hospital Ownership,...,Readmission national comparison,Readmission national comparison footnote,Patient experience national comparison,Patient experience national comparison footnote,Effectiveness of care national comparison,Effectiveness of care national comparison footnote,Timeliness of care national comparison,Timeliness of care national comparison footnote,Efficient use of medical imaging national comparison,Efficient use of medical imaging national comparison footnote
10,10021,DALE MEDICAL CENTER,126 HOSPITAL AVE,OZARK,AL,36360,DALE,3347742601,Acute Care Hospitals,Government - Hospital District or Authority,...,Same as the national average,Results are not available for this reporting p...,Above the national average,Results are not available for this reporting p...,Same as the national average,NaN,Above the national average,NaN,Same as the national average,Results are not available for this reporting p...
11,10022,CHEROKEE MEDICAL CENTER,400 NORTHWOOD DR,CENTRE,AL,35960,CHEROKEE,2569275531,Acute Care Hospitals,Voluntary non-profit - Private,...,Same as the national average,Results are not available for this reporting p...,Above the national average,Results are not available for this reporting p...,Same as the national average,NaN,Same as the national average,NaN,Not Available,Results are not available for this reporting p...
14,10029,EAST ALABAMA MEDICAL CENTER,2000 PEPPERELL PARKWAY,OPELIKA,AL,36801,LEE,3347493411,Acute Care Hospitals,Government - Hospital District or Authority,...,Above the national average,Results are not available for this reporting p...,Above the national average,Results are not available for this reporting p...,Same as the national average,NaN,Above the national average,NaN,Same as the national average,Results are not available for this reporting p...
15,10032,WEDOWEE HOSPITAL,209 NORTH MAIN STREET,WEDOWEE,AL,36278,RANDOLPH,2563572111,Acute Care Hospitals,Government - Hospital District or Authority,...,Same as the national average,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Same as the national average,NaN,Same as the national average,NaN,Not Available,Results are not available for this reporting p...
17,10034,COMMUNITY HOSPITAL INC,805 FRIENDSHIP ROAD,TALLASSEE,AL,36078,ELMORE,3342836541,Acute Care Hospitals,Voluntary non-profit - Private,...,Same as the national average,Results are not available for this reporting p...,Same as the national average,Results are not available for this reporting p...,Same as the national average,NaN,Same as the national average,NaN,Not Available,Results are not available for this reporting p...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4777,670078,BAPTIST EMERGENCY HOSPITAL,16088 SAN PEDRO,SAN ANTONIO,TX,78232,BEXAR,2104024092,Acute Care Hospitals,Proprietary,...,Same as the national average,Results are not available for this reporting p...,Above the national average,Results are not available for this reporting p...,Same as the national average,Results are not available for this reporting p...,Above the national average,Results are not available for this reporting p...,Above the national average,Results are not available for this reporting p...
4779,670080,SETON MEDICAL CENTER HARKER HEIGHTS,850 W CENTRAL TEXAS EXPRESSWAY,HARKER HEIGHTS,TX,76548,BELL,2549538342,Acute Care Hospitals,Proprietary,...,Same as the national average,Results are not available for this reporting p...,Above the national average,Results are not available for this reporting p...,Same as the national average,Results are not available for this reporting p...,Same as the national average,Results are not available for this reporting p...,Same as the national average,Results are not available for this reporting p...
4780,670082,BAYLOR SCOTT AND WHITE MEDICAL CENTER MCKINNEY,5252 WEST UNIVERSITY DRIVE,MC KINNEY,TX,75071,COLLIN,4697642200,Acute Care Hospitals,Voluntary non-profit - Private,...,Same as the national average,Results are not available for this reporting p...,Above the national average,Results are not available for this reporting p...,Same as the national average,Results are not available for this reporting p...,Above the national average,Results are not available for this reporting p...,Same as the national average,Results are not available for this reporting p...
4782,670085,TEXAS HEALTH HARRIS METHODIST HOSPITAL ALLIANCE,10864 TEXAS HEALTH TRAIL,FORT WORTH,TX,76244,TARRANT,6822122000,Acute Care Hospitals,Voluntary non-profit - Private,...,Same as the national average,Results are not available for this reporting p...,Same as the national average,Results are not available for this reporting p...,Same as the national average,Results are not available for this reporting p...,Same as the national average,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...
4784,670088,BAYLOR SCOTT & WHITE MEDICAL CENTER- COLLEGE S...,700 SCOTT & WHITE DRIVE,COLLEGE STATION,TX,77845,BRAZOS,9796913701,Acute Care Hospitals,Voluntary non-profit - Private,...,Same as the national average,Results are not available for this reporting p...,Above the national average,Results are not available for this reporting p...,Same as the national average,Results are not available for this reporting p...,Above the national average,Results are not available for this reporting p...,Same as the national average,Results are not available for this reporting p...

In [15]:
df.columns

Index(['Provider ID', 'Hospital Name', 'Address', 'City', 'State', 'ZIP Code',
       'County Name', 'Phone Number', 'Hospital Type', 'Hospital Ownership',
       'Emergency Services', 'Meets criteria for meaningful use of EHRs',
       'Hospital overall rating', 'Hospital overall rating footnote',
       'Mortality national comparison',
       'Mortality national comparison footnote',
       'Safety of care national comparison',
       'Safety of care national comparison footnote',
       'Readmission national comparison',
       'Readmission national comparison footnote',
       'Patient experience national comparison',
       'Patient experience national comparison footnote',
       'Effectiveness of care national comparison',
       'Effectiveness of care national comparison footnote',
       'Timeliness of care national comparison',
       'Timeliness of care national comparison footnote',
       'Efficient use of medical imaging national comparison',
       'Efficient use of medical imaging national comparison footnote'],
      dtype='object')

In [16]:
df["Safety of care national comparison"]

0         Above the national average
1       Same as the national average
2       Same as the national average
3                      Not Available
4                      Not Available
                    ...
4807                   Not Available
4808                   Not Available
4809                   Not Available
4810                   Not Available
4811                   Not Available
Name: Safety of care national comparison, Length: 4812, dtype: object

In [17]:
df[["Patient experience national comparison","Provider ID"]]

     Patient experience national comparison  Provider ID
0                Below the national average        10001
1              Same as the national average        10005
2                Below the national average        10006
3              Same as the national average        10007
4                             Not Available        10008
...                                     ...          ...
4807                          Not Available       670118
4808                          Not Available       640001
4809                          Not Available       650001
4810                          Not Available       650003
4811                          Not Available       660001

[4812 rows x 2 columns]

In [18]:
set(df["Patient experience national comparison"])

{'Above the national average',
 'Below the national average',
 'Not Available',
 'Same as the national average'}

In [19]:
df[["Hospital Type","Safety of care national comparison"]]

             Hospital Type Safety of care national comparison
0     Acute Care Hospitals         Above the national average
1     Acute Care Hospitals       Same as the national average
2     Acute Care Hospitals       Same as the national average
3     Acute Care Hospitals                      Not Available
4     Acute Care Hospitals                      Not Available
...                    ...                                ...
4807  Acute Care Hospitals                      Not Available
4808  Acute Care Hospitals                      Not Available
4809  Acute Care Hospitals                      Not Available
4810  Acute Care Hospitals                      Not Available
4811  Acute Care Hospitals                      Not Available

[4812 rows x 2 columns]

In [20]:
set(df["Hospital Type"])

{'Acute Care Hospitals', 'Childrens', 'Critical Access Hospitals'}

In [26]:
df.loc[(df["Safety of care national comparison"]=="Not Available")]["Hospital Type"].value_counts()

Critical Access Hospitals    1342
Acute Care Hospitals          727
Childrens                      99
Name: Hospital Type, dtype: int64

In [27]:
df.loc[(df["Safety of care national comparison"]=="Not Available")]["Hospital Type"].value_counts()[0]

1342

# End of skilling 3